# Generated by Django 5.2.8 on 2025-11-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("stock", models.IntegerField(default=0)),
                ("disponible", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("num_pedido", models.IntegerField(default=0)),
                ("estado", models.CharField(default="Nuevo", max_length=50)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "coste_entrega",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "precio_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "metodo_pago",
                    models.CharField(default="No especificado", max_length=50),
                ),
                ("direccion_envio", models.CharField(blank=True, max_length=255)),
                ("telefono_contacto", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
    ]
