# Generated by Django 5.2.8 on 2025-11-29 17:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='coste_entrega',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.99'), max_digits=12),
        ),
    ]
