# Generated by Django 5.2.6 on 2025-11-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='talla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
