# Generated by Django 5.2.8 on 2025-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_producto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="precio_total",
        ),
        migrations.AlterField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("nuevo", "Nuevo"),
                    ("procesando", "Procesando"),
                    ("enviado", "Enviado"),
                    ("entregado", "Entregado"),
                    ("cancelado", "Cancelado"),
                ],
                default="nuevo",
                max_length=20,
            ),
        ),
    ]
