# Generated by Django 5.2.6 on 2025-11-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_itempedido_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='talla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
