# Generated by Django 5.2.8 on 2025-11-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_producto_precio_total_alter_producto_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("nuevo", "Nuevo"),
                    ("pendiente_pago", "Pendiente de Pago"),
                    ("listo_envio", "Listo para Envío"),
                    ("enviado", "Enviado"),
                    ("reparto", "Reparto"),
                    ("entregado", "Entregado"),
                    ("cancelado", "Cancelado"),
                ],
                default="nuevo",
                max_length=20,
            ),
        ),
    ]
