# Generated by Django 5.2.8 on 2025-11-12 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_producto_estado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="disponible",
            new_name="esta_disponible",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="coste_entrega",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="descuento",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="direccion_envio",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="impuestos",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="metodo_pago",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="num_pedido",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="telefono_contacto",
        ),
        migrations.AddField(
            model_name="producto",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="producto",
            name="es_destacado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_actualizacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="producto",
            name="genero",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
        migrations.AddField(
            model_name="producto",
            name="material",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_oferta",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
