# Generated by Django 5.2.8 on 2025-11-12 19:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_disponible_producto_esta_disponible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="genero",
            field=models.CharField(
                choices=[
                    ("perro", "Perro"),
                    ("gato", "Gato"),
                    ("ave", "Ave"),
                    ("roedor", "Roedor"),
                    ("reptil", "Reptil"),
                    ("pecera", "Pecera"),
                    ("otro", "Otro"),
                ],
                default="perro",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
