# Generated by Django 5.2.8 on 2025-11-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_categoria_marca_imagenproducto_tallaproducto'),
        ('home', '0007_cliente_pedido_itempedido'),
    ]

    operations = [
    ]
